// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trainStation.Data;

#nullable disable

namespace trainStation.Migrations
{
    [DbContext(typeof(trainStationContext))]
    partial class trainStationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("trainStation.Model.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainID");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrival = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Departure = new DateTime(2026, 5, 1, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Platform = 0,
                            TrainID = 1
                        },
                        new
                        {
                            Id = 2,
                            Arrival = new DateTime(2026, 5, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Departure = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = 2,
                            TrainID = 2
                        },
                        new
                        {
                            Id = 3,
                            Arrival = new DateTime(2026, 5, 1, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Platform = 5,
                            TrainID = 3
                        });
                });

            modelBuilder.Entity("trainStation.Model.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<bool>("SpecialHandling")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Train");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Glacier Express",
                            Length = 160.0,
                            Mass = 0.0,
                            Name = "Zermatt-St.Moritz",
                            Service = 0,
                            SpecialHandling = false
                        },
                        new
                        {
                            Id = 2,
                            Cargo = 3,
                            Company = "BNSF Railway",
                            Length = 2000.0,
                            Mass = 15000.0,
                            Name = "BNSF Transcon",
                            Service = 1,
                            SpecialHandling = false
                        },
                        new
                        {
                            Id = 3,
                            Cargo = 0,
                            Company = "JR Central",
                            Length = 400.0,
                            Mass = 0.0,
                            Name = "Shinkansen Nozomi",
                            Service = 0,
                            SpecialHandling = false
                        });
                });

            modelBuilder.Entity("trainStation.Model.Schedule", b =>
                {
                    b.HasOne("trainStation.Model.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("trainStation.Model.Train", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
